server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:~/tiny-stock;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # 개발용: 매번 테이블 생성/삭제
    show-sql: true            # 콘솔에 SQL 찍기
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true           # H2 콘솔 사용 (localhost:8081/tiny-stock)
logging:
  level:
    org.hibernate.SQL: debug